OT93-130
alkemyTech/OT-93-Server pull request #114
Opened 2021-11-19 20:05 UTC by joaquinnieva

agregue la pagina para el notfound 404 y lo agregue al router

2021-11-21 19:12 UTC, Andres-Pro-666 requested changes

2021-11-21 19:12 UTC, Andres-Pro-666 commented on src/Components/NotFound/index.js
> +        <h1>No puedo encontrar esta página</h1>
string hardcode nooo. . y busca alguna imagen o algo que quede un poco mas lindo ... hay muchas por ahi .

2021-11-22 16:09 UTC, Andres-Pro-666 commented
arreglar conflict

2021-11-22 21:33 UTC, joaquinnieva commented on src/Components/NotFound/index.js
> +        <h1>No puedo encontrar esta página</h1>
ya arregle todo

2021-11-23 15:29 UTC, merged