OT93-52
alkemyTech/OT-93-Server pull request #47
Opened 2021-11-01 20:31 UTC by deztidev

- Created Home component
- Created Home styles
- Added global font

2021-11-03 13:05 UTC, Andres-Pro-666 commented on src/pages/Home/Component.js
> +              <Row
esto asi no va tenes que hacer un componente slick que se llame dos veces creo que lo habia mostrado...aca me estas harcodeando absolutamente todo eso no va...
en el home tenes que tener 4 componentes solamennte .. el slick que se llama 2 veces.. el slidar que es otro componente .. y el titulo... que tiene que ser el componente q renderiza titulos..

2021-11-03 13:06 UTC, Andres-Pro-666 requested changes
creo que vos tenes todas las tareas de los componentes del home tenes q hacer los componente y llamarlos aca  las pages tienen que ser solo contenedores  q llaman a otros subcomponentes ... no quiero texto harcodeado en las pges ni en los componentes tambien se lo habia dicho... los label debotones van a constantes ...

2021-11-03 13:39 UTC, deztidev commented on src/pages/Home/Component.js
> +              <Row
Entendí que había que implementarlo así porque en la tarea decía que debía mostrar un placeholder de esos componentes, por lo que pensé que se implementaban después. El componente de título no me lo pedía, por eso no lo llamé. El componente slick no lo encuentro en reactstrap ni en bootstrap ¿Lo traigo de otra librería? ¿Y los títulos h2 también van en constantes?

2021-11-04 14:43 UTC, Andres-Pro-666 commented on src/pages/Home/Component.js
> +              <Row
no el titulo se va atraer de organization de la api .
tmb vas a tener que hacer lo mismo que tenes que hacer para traer los datos del slide o simplemente podes hacer los dos llamados en un solo sagas para traer los datos.

2021-11-05 14:07 UTC, merged