Members reducer finished.
alkemyTech/OT-93-Server pull request #81
Opened 2021-11-11 03:22 UTC by Vintersorganic

Reducer para el ticket OT93-67 que hicimos con Nico.

2021-11-11 13:13 UTC, Andres-Pro-666 requested changes

2021-11-11 13:13 UTC, Andres-Pro-666 commented on src/core/state/orgMembers/sagas.js
> +    yield error;
esto asi creo que te va a explotar hay que usar el componente para mostrar errores

2021-11-11 15:58 UTC, Vintersorganic commented on src/core/state/orgMembers/sagas.js
> +    yield error;
Listo, subido el commit con lo que pediste.

2021-11-12 01:03 UTC, Andres-Pro-666 requested changes

2021-11-12 01:03 UTC, Andres-Pro-666 commented on src/core/state/orgMembers/sagas.js
> +        icon: 'danger',
veo string hardcode ... pasa ese danger a una constante ERROR o algo asi

2021-11-12 01:06 UTC, Andres-Pro-666 commented
lo mergeo pero hace el cambio en el proximo pr o cambio

2021-11-12 01:06 UTC, merged